services:
  builder:
    image: ghcr.io/${GH_OWNER}/${GH_REPO}:${APP_VERSION}
    pull_policy: always 
    env_file:
      - .env
    environment:
      - LRELEASE=${LRELEASE}
      - BUILD=${BUILD}
      - VERSION=${VERSION}
      - FONTS_DIR=${FONTS_DIR}
      - TGZ_NAME=${TGZ_NAME}       
    volumes:
      - ./dist:/app/dist
      - ./KoboRoot:/app/KoboRoot
      - ./fonts:/app/fonts 
    command: ["--build", "${BUILD}", "--version", "${VERSION}", "--fonts", "${FONTS_DIR}", "--name", "${TGZ_NAME}"]
