services:
  builder:
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env
    environment:
      - LRELEASE=${LRELEASE}
      - BUILD=${BUILD}
      - VERSION=${VERSION}
      - FONTS_DIR=${FONTS_DIR}       
    volumes:
      - ./dist:/app/dist
      - ./KoboRoot:/app/KoboRoot
      - ./fonts:/app/fonts 
    command: ["--build", "${BUILD}", "--version", "${VERSION}", "--fonts", "${FONTS_DIR}"]
