services:
  builder:
    image: ghcr.io/${GH_OWNER}/${GH_REPO}:${APP_VERSION}
    pull_policy: always 
    env_file:
      - .env
    volumes:
      - ${DIST_DIR}:/app/dist
      - ${KOBOROOT_DIR}:/app/KoboRoot
      - ${FONTS_DIR}:/app/fonts 
    command: ["--build", "${BUILD}", "--version", "${VERSION}", "--fonts", "${FONTS_DIR}", "--name", "${TGZ_NAME}"]
