name: Build
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository_owner }}/kobo-tieng-viet:latest
    steps:
    - name: Install git and make
      run: |
        apt-get update
        apt-get install -y git make
    - name: Checkout
      uses: actions/checkout@v5
      with:
        submodules: true
    - name: Build
      run: make all
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: kobo-tieng-viet
        path: ./dist/KoboRoot.tgz
