name: Docker Publish

on: [workflow_dispatch]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Free disk space
        run: |
          echo "Before cleanup:"
          df -h
          docker system prune -af
          docker volume prune -f
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          echo "After cleanup:"
          df -h

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version
        id: vars
        run: |
          VERSION="$(shell date +%Y%m%d)"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfile.base  
          push: true
          platforms: linux/amd64   # thêm linux/arm64 nếu cần đa kiến trúc
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}:${{ steps.vars.outputs.version }}
            ${{ env.REGISTRY }}/${{ github.repository }}:base
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=image,compression=zstd
